name: Run Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: sdp-mu796-csit-mulesoft
    container:
      image: python:3.12.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  #    - name: Set up Python
  #      uses: actions/setup-python@v2
   #     with:
    #      python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl
          pip install PyGithub
              

      - name: Create branch in GitHub
        run: python branch.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
