name: Run Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        run: |
          pip install pandas openpyxl
          pip install PyGithub
              

      - name: Create branch in GitHub
        run: python branching.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
